// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boqtxcmhjluucrteecwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvcXR4Y21oamx1dWNydGVlY3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTMzOTUsImV4cCI6MjA3MjUyOTM5NX0.ptq3gEDFSUO4V0pyTWuYxBx9tVNTsD3eGVBt9Aezh8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});